### ISSUE TITLE
Where is the adb for android?

### ISSUE THREAD

**Issue by weakdancer** [kosborn/p2p-adb#5]
> An install has/supports adb (I believe stock comes with adb, otherwise you could probably add it)

I saw this and does that means I could not use adb on android right now?
I could not find it anywhere.
and file fakebackup.ab in the folder includes?
what is that for?
I've consider about adb on openwrt,but it seems that no body have done it before.
http://myswap.sinaapp.com/wd/openwrtadb

**Comment by Hackrylix** [comment]
adb can easily be installed by installing the Android SDK on your computer.
Don't know about an openwrt installation.

**Comment by parkour86** [comment]
I too would like to know more about the fakebackup.ab file. I believe it's used to gain root (root4.x.sh) on a phone that hasn't been rooted. My question is, if you run the root4.x.sh script on a phone that's not rooted is it reverse-able? I want to test it out on one of my phones but I don't want it permanently rooted.

**Comment by kosborn** [comment]
@weakdancer For your computer, you can grab adb from the android sdk packages. For your phone, you have a few options: 4.x comes with the adb binary (as far as I know). Cyanogenmod 9/10 & AOKP both come with the adb binary. You can rip the adb binary out of a stock rom. 

@parkour86 @weakdancer fakeupdate.ab is used for root4.x.sh, and the update file was found here: [XDA Developers](http://forum.xda-developers.com/showthread.php?t=1886460). Currently, root4.x.sh isn't fully supported... I have an update I will be pushing tomorrow or Saturday that will finish it up. I've effectively just re-implemented the exploit I found on [XDA Developers](http://forum.xda-developers.com/showthread.php?t=1886460). It's not 100%, but it's worked on the Nexus devices I have to test and the other devices marked in that thread. 

**Note**: root4.x.sh is probably not the fastest way to root someone's phone, but I included it just because not having to unlock my phone and wipe my data is way convenient, and I thought others might want to also (for whatever reason).

**Comment by kiamgrebgnur** [comment]
Hi
First: Great work I'm excited.
I got the adb file from CM9 but can't execute it on my desire. Do I need other software too ?

**Comment by kosborn** [comment]
@kiamgrebgnur I don't know what you mean "can't execute it". You're trying to execute the adb binary you got from your phone on your computer? That's not likely to work, they're two different architectures. Are you running windows, linux, or os x? Windows is not supported (at all). In any instance, get adb from the Android SDK. It's part of the platform tools package.

**Comment by kiamgrebgnur** [comment]
No no :)
Ich have adb extracted from the CM9 zip and pushed it to my htc.
If I try to start it I get a segmentation fault (http://forum.xda-developers.com/showthread.php?p=32426081#post32426081)

**Comment by kosborn** [comment]
Hmm. Odd. Well, I'm working on adding a statically compiled arm version of adb that should work on just about an device running Linux on arm. If you can wait a few days, I'll have that out and ready to test.

**Comment by kosborn** [comment]
Note: I've pushed a statically built adb binary for ARM devices (phones). Check it at [line #16](https://github.com/kosborn/p2p-adb/blob/master/run.sh#L16), set tryStaticADB=0 to tryStaticADB=1, and it will start using statically compiled arm version.

Please give this is a test, and report any issues you have with it. If I get A+++ responses, then I'll enable it by default from ARM devices.
